name: BombDefusal
description: Place time bombs that require specialist tools or knowledge to defuse.
author: Adzwoolly (Adam Woollen)
main: uk.adzwoolly.mc.bombdefusal.BombDefusalMain
version: 1.0
commands:
  defuse:
    description: Defuse a bomb!
    usage: /defuse <bomb_name>